# Generated by Django 4.2.4 on 2023-08-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_stream_platforms_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream_Platforms',
            new_name='StreamPlatform',
        ),
    ]
