# Generated by Django 4.2.4 on 2023-08-18 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='showlist',
            new_name='showname',
        ),
        migrations.AlterField(
            model_name='show',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showname', to='watchlist.streamplatform'),
        ),
    ]
