# Generated by Django 4.2.4 on 2023-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0011_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='avg_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='show',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
