# Generated by Django 4.2.4 on 2023-08-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0012_show_avg_ratings_show_number_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
